---
name: Documentation
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  preview:
    name: PR Preview
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    env:
      DOCS_VERSION: PR-${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: sha8
      - uses: actions/setup-python@v2
      - run: python --version
      - uses: jwlawson/actions-setup-cmake@v1.9
      - run: cmake --version
      - name: Install Sphinx
        run: python -m pip install -r docs/requirements.txt
      - run: sphinx-build --version
      - name: Configure
        run: >
          ctest -VV
          -D STEPS=clean\;configure
          -D DOCS_VERSION=${{ env.DOCS_VERSION }}
          -S FairCMakeModules_test.cmake
      - name: Generate Docs
        run: ctest -VV -D STEPS=docs -S FairCMakeModules_test.cmake
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build/docs/html
          target-folder: ${{ env.DOCS_VERSION }}
          clean: true
      - name: Comment PR with preview link
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            [:paperclip: Docs preview](https://fairrootgroup.github.io/FairCMakeModules/${{ env.DOCS_VERSION }}/)
  latest:
    name: Generate
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version
      - uses: jwlawson/actions-setup-cmake@v1.9
      - run: cmake --version
      - name: Install Sphinx
        run: python -m pip install -r docs/requirements.txt
      - run: sphinx-build --version
      - name: Generate Docs
        run: >
          ctest -VV
          -D STEPS=clean\;configure\;docs
          -S FairCMakeModules_test.cmake
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build/docs/html
          target-folder: latest
          clean: true
