---
name: Documentation
on: [push, pull_request_target]
jobs:
  gen:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python --version
      - uses: jwlawson/actions-setup-cmake@v1.9
      - run: cmake --version
      - name: Install Sphinx
        run: python -m pip install -r docs/requirements.txt
      - run: sphinx-build --version
      - name: Configure
        run: ctest -VV -D "STEPS=clean;configure" -S FairCMakeModules_test.cmake
      - name: Generate Docs
        run: ctest -VV -D "STEPS=docs" -S FairCMakeModules_test.cmake
      - name: 'Comment PR with preview link'
        uses: mshick/add-pr-comment@v1
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            **Hello MASTER**
