---
name: Documentation
on:
  push:
    branches:
      - main
jobs:
  latest:
    name: Generate
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
      - run: python --version
      - uses: jwlawson/actions-setup-cmake@v1.14
      - run: cmake --version
      - name: Install Sphinx
        run: python -m pip install -r docs/requirements.txt
      - run: sphinx-build --version
      - name: Generate Docs
        run: >
          ctest -VV
          -D STEPS=clean\;configure\;docs
          -S FairCMakeModules_test.cmake
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build/docs/html
          target-folder: latest
          clean: true
