---
name: Test
on:
  push:
    branches:
    - '**'
    - '!pr/**'
  pull_request:
jobs:
  main:
    strategy:
      matrix:
        cmake: ['3.21', '3.20', '3.19', '3.18', '3.17', '3.16', '3.15']
        os: [ubuntu-latest]
        name: [Linux]
        include:
          - cmake: '3.20'
            os: macos-latest
            name: macOS
    name: ${{ matrix.name }} - CMake ${{ matrix.cmake }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: ${{ matrix.cmake }}
      - name: Use cmake
        run: cmake --version
      - name: Configure
        run: ctest -VV -D "STEPS=clean;configure" -S FairCMakeModules_test.cmake
      - name: Build
        run: ctest -VV -D "STEPS=build" -S FairCMakeModules_test.cmake
      - name: Install
        run: ctest -VV -D "STEPS=install" -S FairCMakeModules_test.cmake
      - name: Test
        run: >
          ctest -V --output-on-failure -D "STEPS=test"
          -S FairCMakeModules_test.cmake
